language: python
python:
- '2.3'
- '2.4'
- '2.5'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'

install:
    - pip install coveralls
    - pip install mock==2.0
    - pip install pytest
    - pip install pytest-cov
script:
    - nosetests --exe --with-coverage --cover-package=escalator
after_success:
    - coveralls
